website1: https://test-stand.gb.ru/gateway/login
website2: https://test-stand.gb.ru/api/posts
website3: https://test-stand.gb.ru/gateway/posts
username: maxecho228
password: a422eef197
title: title placeholder
description: description placeholder
content: content placeholder